# Generated by Django 4.2.5 on 2023-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name_uz',
            field=models.CharField(default='HomePage', max_length=200),
            preserve_default=False,
        ),
    ]
