# Generated by Django 4.2.5 on 2023-09-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_description_homepage_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
    ]
